"""Se modifica las tablas de prescripciones y prescripciones detalles

Revision ID: 1b6edcf55c3e
Revises: e2e4bb5cf1ab
Create Date: 2024-01-11 17:44:44.790262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b6edcf55c3e'
down_revision = 'e2e4bb5cf1ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people_prescription', schema=None) as batch_op:
        batch_op.drop_column('pepr_medical_indications')

    with op.batch_alter_table('people_prescription_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prde_medicine', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('prde_medical_indications', sa.String(length=4000), nullable=False))
        batch_op.drop_column('prde_details')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people_prescription_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prde_details', sa.VARCHAR(length=4000), nullable=False))
        batch_op.drop_column('prde_medical_indications')
        batch_op.drop_column('prde_medicine')

    with op.batch_alter_table('people_prescription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pepr_medical_indications', sa.VARCHAR(length=4000), nullable=False))

    # ### end Alembic commands ###
