"""Se corrige los campos en las tablas de prescripcion y detalles de prescripcion

Revision ID: 286b22b8d2f4
Revises: b07dcf5cd246
Create Date: 2024-01-22 16:03:56.465029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '286b22b8d2f4'
down_revision = 'b07dcf5cd246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_people_prescription')
    with op.batch_alter_table('people_prescription', schema=None) as batch_op:
        batch_op.drop_constraint('fk_people_prescription_pepr_phar_id', type_='foreignkey')
        batch_op.drop_column('pepr_phar_id')
        batch_op.drop_column('pepr_date_dispatched')
        batch_op.drop_column('pepr_dispatched')

    with op.batch_alter_table('people_prescription_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prde_date_dispatched', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('prde_user_dispatcher_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pepr_dispatched', sa.String(length=1), nullable=True))
        batch_op.create_foreign_key("fk_dispatcher", 'users', ['prde_user_dispatcher_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people_prescription_details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pepr_dispatched')
        batch_op.drop_column('prde_user_dispatcher_id')
        batch_op.drop_column('prde_date_dispatched')

    with op.batch_alter_table('people_prescription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pepr_dispatched', sa.VARCHAR(length=1), nullable=True))
        batch_op.add_column(sa.Column('pepr_date_dispatched', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('pepr_phar_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_people_prescription_pepr_phar_id', 'pharmacist', ['pepr_phar_id'], ['phar_id'])

    op.create_table('_alembic_tmp_people_prescription',
    sa.Column('pepr_id', sa.INTEGER(), nullable=False),
    sa.Column('pepr_peop_id', sa.INTEGER(), nullable=False),
    sa.Column('pepr_doct_id', sa.INTEGER(), nullable=False),
    sa.Column('pepr_state', sa.VARCHAR(length=1), nullable=False),
    sa.Column('pepr_created_at', sa.DATETIME(), nullable=True),
    sa.Column('pepr_user_created_id', sa.INTEGER(), nullable=False),
    sa.Column('pepr_updated_at', sa.DATETIME(), nullable=True),
    sa.Column('pepr_user_updated_id', sa.INTEGER(), nullable=True),
    sa.Column('pepr_dx', sa.VARCHAR(length=4000), nullable=True),
    sa.ForeignKeyConstraint(['pepr_doct_id'], ['doctors.doct_id'], name="fk_pepr_doct"),
    sa.ForeignKeyConstraint(['pepr_peop_id'], ['people.peop_id'], name="fk_pepr_peop"),
    sa.ForeignKeyConstraint(['pepr_user_created_id'], ['users.user_id'], name="fk_pepr_created"),
    sa.ForeignKeyConstraint(['pepr_user_updated_id'], ['users.user_id'], name="fk_pepr_updated"),
    sa.PrimaryKeyConstraint('pepr_id')
    )
    # ### end Alembic commands ###
