"""correccion de nombre de campo de detalles de prescripcion

Revision ID: a8169ad21c6d
Revises: 227f0fc440b3
Create Date: 2024-01-22 16:45:07.146467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8169ad21c6d'
down_revision = '227f0fc440b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_people_prescription_details')
    with op.batch_alter_table('people_prescription_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prde_dispatched', sa.String(length=1), nullable=False))
        batch_op.drop_column('pepr_dispatched')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people_prescription_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pepr_dispatched', sa.VARCHAR(length=1), nullable=True))
        batch_op.drop_column('prde_dispatched')

    op.create_table('_alembic_tmp_people_prescription_details',
    sa.Column('prde_id', sa.INTEGER(), nullable=False),
    sa.Column('prde_dispatched', sa.VARCHAR(length=1), nullable=False),
    sa.Column('prde_pepr_id', sa.INTEGER(), nullable=False),
    sa.Column('prde_state', sa.VARCHAR(length=1), nullable=False),
    sa.Column('prde_created_at', sa.DATETIME(), nullable=True),
    sa.Column('prde_user_created_id', sa.INTEGER(), nullable=False),
    sa.Column('prde_updated_at', sa.DATETIME(), nullable=True),
    sa.Column('prde_user_updated_id', sa.INTEGER(), nullable=True),
    sa.Column('prde_medicine', sa.VARCHAR(length=100), nullable=False),
    sa.Column('prde_medical_indications', sa.VARCHAR(length=4000), nullable=False),
    sa.Column('prde_date_dispatched', sa.DATETIME(), nullable=True),
    sa.Column('prde_user_dispatcher_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['prde_pepr_id'], ['people_prescription.pepr_id'], ),
    sa.ForeignKeyConstraint(['prde_user_created_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['prde_user_dispatcher_id'], ['users.user_id'], name='fk_dispatcher'),
    sa.ForeignKeyConstraint(['prde_user_updated_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('prde_id')
    )
    # ### end Alembic commands ###
