"""Se agregan instituciones y farmaceuticos

Revision ID: acbf53d057a3
Revises: 29f0231e3a4b
Create Date: 2024-01-08 13:45:13.022229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acbf53d057a3'
down_revision = '29f0231e3a4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('inst_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inst_bussiness_name', sa.String(length=200), nullable=False),
    sa.Column('inst_trade_name', sa.String(length=200), nullable=False),
    sa.Column('inst_itin', sa.String(length=30), nullable=False),
    sa.Column('inst_state', sa.String(length=1), nullable=False),
    sa.Column('inst_created_at', sa.DateTime(), nullable=True),
    sa.Column('inst_user_created_id', sa.Integer(), nullable=False),
    sa.Column('inst_updated_at', sa.DateTime(), nullable=True),
    sa.Column('inst_user_updated_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['inst_user_created_id'], [
                                'users.user_id'], name="fk_inst_created"),
        sa.ForeignKeyConstraint(['inst_user_updated_id'], [
                                'users.user_id'], name="fk_inst_updated"),
    sa.PrimaryKeyConstraint('inst_id'),
    sa.UniqueConstraint('inst_bussiness_name', 'inst_trade_name', 'inst_itin', name='uq_institution_info')
    )
    op.create_table('medical_especialties',
    sa.Column('mees_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mees_desc', sa.String(length=100), nullable=False),
    sa.Column('mees_state', sa.String(length=1), nullable=False),
    sa.Column('mees_created_at', sa.DateTime(), nullable=True),
    sa.Column('mees_user_created_id', sa.Integer(), nullable=False),
    sa.Column('mees_updated_at', sa.DateTime(), nullable=True),
    sa.Column('mees_user_updated_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mees_user_created_id'], ['users.user_id'], name="fk_mees_created"),
        sa.ForeignKeyConstraint(['mees_user_updated_id'], [
                                'users.user_id'], name="fk_mees_updated"),
    sa.PrimaryKeyConstraint('mees_id'),
    sa.UniqueConstraint('mees_desc')
    )
    op.create_table('pharmacist',
    sa.Column('phar_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phar_peop_id', sa.Integer(), nullable=False),
    sa.Column('phar_inst_id', sa.Integer(), nullable=True),
    sa.Column('phar_state', sa.String(length=1), nullable=False),
    sa.Column('phar_created_at', sa.DateTime(), nullable=True),
    sa.Column('phar_user_created_id', sa.Integer(), nullable=False),
    sa.Column('phar_updated_at', sa.DateTime(), nullable=True),
    sa.Column('phar_user_updated_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['phar_inst_id'], ['institutions.inst_id'], ),
    sa.ForeignKeyConstraint(['phar_peop_id'], ['people.peop_id'], ),
        sa.ForeignKeyConstraint(['phar_user_created_id'], [
                                'users.user_id'], name="fk_phar_created"),
        sa.ForeignKeyConstraint(['phar_user_updated_id'], [
                                'users.user_id'], name="fk_phar_updated"),
    sa.PrimaryKeyConstraint('phar_id')
    )
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doct_mees_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('doct_inst_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'institutions', ['doct_inst_id'], ['inst_id'])
        batch_op.create_foreign_key(None, 'medical_especialties', ['doct_mees_id'], ['mees_id'])

    with op.batch_alter_table('people_prescription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pepr_phar_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pepr_dispatched', sa.String(length=1), nullable=True))
        batch_op.add_column(sa.Column('pepr_date_dispatched', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'pharmacist', ['pepr_phar_id'], ['phar_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people_prescription', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pepr_date_dispatched')
        batch_op.drop_column('pepr_dispatched')
        batch_op.drop_column('pepr_phar_id')

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('doct_inst_id')
        batch_op.drop_column('doct_mees_id')

    op.drop_table('pharmacist')
    op.drop_table('medical_especialties')
    op.drop_table('institutions')
    # ### end Alembic commands ###
