"""Se corrige los campos en las tablas de prescripcion y detalles de prescripcion

Revision ID: b07dcf5cd246
Revises: 1b6edcf55c3e
Create Date: 2024-01-22 15:57:08.002754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b07dcf5cd246'
down_revision = '1b6edcf55c3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people_prescription', schema=None) as batch_op:
        batch_op.drop_constraint('fk_people_prescription_pepr_phar_id', type_='foreignkey')
        batch_op.drop_column('pepr_date_dispatched')
        batch_op.drop_column('pepr_dispatched')
        batch_op.drop_column('pepr_phar_id')

    with op.batch_alter_table('people_prescription_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prde_date_dispatched', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('prde_user_dispatcher_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pepr_dispatched', sa.String(length=1), nullable=True))
        batch_op.create_foreign_key("fk_dispatcher", 'users', ['prde_user_dispatcher_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people_prescription_details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pepr_dispatched')
        batch_op.drop_column('prde_user_dispatcher_id')
        batch_op.drop_column('prde_date_dispatched')

    with op.batch_alter_table('people_prescription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pepr_phar_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('pepr_dispatched', sa.VARCHAR(length=1), nullable=True))
        batch_op.add_column(sa.Column('pepr_date_dispatched', sa.DATETIME(), nullable=True))
        batch_op.create_foreign_key('fk_people_prescription_pepr_phar_id', 'pharmacist', ['pepr_phar_id'], ['phar_id'])

    # ### end Alembic commands ###
