"""correccion de nombre de campo

Revision ID: b4cdfde2c8be
Revises: 94552abf1eac
Create Date: 2024-01-22 16:42:26.514945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4cdfde2c8be'
down_revision = '94552abf1eac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people_prescription_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prde_dispatched', sa.String(length=1), nullable=False, default='N'))
        batch_op.drop_column('pepr_dispatched')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people_prescription_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pepr_dispatched', sa.VARCHAR(length=1), nullable=True, default='N'))
        batch_op.drop_column('prde_dispatched')

    # ### end Alembic commands ###
