"""Se agregan cantidad y tipo de empaque

Revision ID: d6c8e0e8e4cc
Revises: fa8dd1970631
Create Date: 2024-01-23 15:11:34.808386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6c8e0e8e4cc'
down_revision = 'fa8dd1970631'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people_prescription_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prde_paty_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('prde_quantity', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_prde_paty_id", 'parcel_type', ['prde_paty_id'], ['paty_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people_prescription_details', schema=None) as batch_op:
        batch_op.drop_constraint("fk_prde_paty_id", type_='foreignkey')
        batch_op.drop_column('prde_quantity')
        batch_op.drop_column('prde_paty_id')

    # ### end Alembic commands ###
