"""Se agregan los campos de indicaciones medicas y diagnosticos a las tablas de prescripcion de personas

Revision ID: e2e4bb5cf1ab
Revises: 46f21604180e
Create Date: 2024-01-11 17:02:22.990097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2e4bb5cf1ab'
down_revision = '46f21604180e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people_prescription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pepr_medical_indications', sa.String(length=4000), nullable=False))
        batch_op.add_column(sa.Column('pepr_dx', sa.String(length=4000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people_prescription', schema=None) as batch_op:
        batch_op.drop_column('pepr_dx')
        batch_op.drop_column('pepr_medical_indications')

    # ### end Alembic commands ###
