"""Se agregan cantidad y tipo de empaque

Revision ID: fa8dd1970631
Revises: 52fb6d51cfdc
Create Date: 2024-01-23 15:10:03.774847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa8dd1970631'
down_revision = '52fb6d51cfdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_people_prescription_details')
    with op.batch_alter_table('people_prescription_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prde_paty_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('prde_quantity', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_prde_paty_id", 'parcel_type', ['prde_paty_id'], ['paty_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people_prescription_details', schema=None) as batch_op:
        batch_op.drop_constraint("fk_prde_paty_id", type_='foreignkey')
        batch_op.drop_column('prde_quantity')
        batch_op.drop_column('prde_paty_id')

    op.create_table('_alembic_tmp_people_prescription_details',
    sa.Column('prde_id', sa.INTEGER(), nullable=False),
    sa.Column('prde_dispatched', sa.VARCHAR(length=1), nullable=True),
    sa.Column('prde_pepr_id', sa.INTEGER(), nullable=False),
    sa.Column('prde_state', sa.VARCHAR(length=1), nullable=False),
    sa.Column('prde_created_at', sa.DATETIME(), nullable=True),
    sa.Column('prde_user_created_id', sa.INTEGER(), nullable=False),
    sa.Column('prde_updated_at', sa.DATETIME(), nullable=True),
    sa.Column('prde_user_updated_id', sa.INTEGER(), nullable=True),
    sa.Column('prde_medicine', sa.VARCHAR(length=100), nullable=False),
    sa.Column('prde_medical_indications', sa.VARCHAR(length=4000), nullable=False),
    sa.Column('prde_date_dispatched', sa.DATETIME(), nullable=True),
    sa.Column('prde_user_dispatcher_id', sa.INTEGER(), nullable=True),
    sa.Column('prde_paty_id', sa.INTEGER(), nullable=True),
    sa.Column('prde_quantity', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['prde_paty_id'], ['parcel_type.paty_id'], name='fk_prde_paty_id'),
    sa.ForeignKeyConstraint(['prde_pepr_id'], ['people_prescription.pepr_id'], ),
    sa.ForeignKeyConstraint(['prde_user_created_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['prde_user_dispatcher_id'], ['users.user_id'], name='fk_dispatcher'),
    sa.ForeignKeyConstraint(['prde_user_updated_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('prde_id')
    )
    # ### end Alembic commands ###
